[package]
name = "bdiff"
version = "0.1.0"
edition = "2021"
authors = ["Ethan Roseman <ethteck@gmail.com>"]
license = "MIT"

[dependencies]
argh = "0.1.10"
encoding_rs = "0.8.32"
iced = { version = "0.10.0", features = ["image", "advanced"] }
iced_core = "0.10.0"
notify = "6.0.1"
palette = "0.7.2"
